### ISSUE TITLE
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob v3.2.8

### ISSUE THREAD

**Issue by TheCloudCrafter** [RockerKitten/BoneAppetit#25]
Ran into an issue running v3.2.2. smoke from fires show up pink due to shader issue.
Rolling back to 3.2.1 has no issue.

[Message:Boneappetit.BoneAppetit] Prepping Kitchen...
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Message:Boneappetit.BoneAppetit] Big thanks to MeatwareMonster!

![image](https://user-images.githubusercontent.com/53633953/228988132-af192164-e56b-4fec-8522-7234b4900fe9.png)

**Comment by sbtoonz** [comment]
I will handle this and upload a fix :) thanks for the report

**Comment by sbtoonz** [comment]
[BoneAppetit.zip](https://github.com/RockerKitten/BoneAppetit/files/11123412/BoneAppetit.zip)
please test and report back

@TheCloudCrafter

**Comment by TheCloudCrafter** [comment]
Provided DLL file imported.
Error persists
```
[Message:Boneappetit.BoneAppetit] Prepping Kitchen...
[Error : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Message:Boneappetit.BoneAppetit] Big thanks to MeatwareMonster!
```
![image](https://user-images.githubusercontent.com/53633953/229165349-3f328320-b678-4638-bb58-53c541e3f415.png)

Rolled back to v3.2.1
Works as intended.

```
[Info   :ModUtilsManagerLog] Building GUI in startup
[Info   :ModUtilsManagerLog] Custom GUI Front & Back built and ready
[Message:Boneappetit.BoneAppetit] Loaded Game VFX and SFX
[Message:Boneappetit.BoneAppetit] Load Complete. Bone Appetit yall.
```
![image](https://user-images.githubusercontent.com/53633953/229166607-c9c17ca2-8f85-4f24-a919-eebd3ee0f490.png)

**Comment by sbtoonz** [comment]
Very odd I do not encounter this error

Can you supply the mod list you are running ?

**Comment by TheCloudCrafter** [comment]
I filtered out some bits, but here is the raw log

I was thinking it might be a mod conflict, but idk what could be messing with the fire.

```
[Info   :   BepInEx] 28 plugins to load
[Info   :   BepInEx] Loading [CartographySkill 2.1.2]
[Info   :   BepInEx] Loading [PlantEverything 1.13.3]
[Info   :   BepInEx] Loading [Backpack Redux 0.6.0]
[Info   :   BepInEx] Loading [Craft From Containers 3.0.0]
[Info   :   BepInEx] Loading [ServerSync Death Tweaks 0.9.1]
[Info   :   BepInEx] Loading [Instant Monster Drop 0.4.0]
[Info   :   BepInEx] Loading [Quick Store 0.2.0]
[Info   :   BepInEx] Loading [AMPED - Auto Map Pins Enhanced 1.3.5]
[Info   :   BepInEx] Loading [FarmGrid 0.2.0]
[Info   :   BepInEx] Loading [Configuration Manager 18.0]
[Info   :   BepInEx] Loading [Jotunn 2.11.2]
[Info   :    Jotunn] Jötunn v2.11.2 loaded successfully
[Info   :   BepInEx] Loading [NPR_ValheimModUtils 1.0.0]
[Info   :   BepInEx] Loading [Crop Utils 1.2.1]
[Info   :   BepInEx] Loading [BoneAppetit 3.2.1]
[Message:Boneappetit.BoneAppetit] Prepping Kitchen...
[Message:Boneappetit.BoneAppetit] Big thanks to MeatwareMonster!
[Info   :   BepInEx] Loading [BlacksmithTools 2.0.2]
[Info   :   BepInEx] Loading [JudesEquipment 2.2.3]
[Info   :   BepInEx] Loading [Server Devcommands 1.45]
[Info   :   BepInEx] Loading [World Edit Commands 1.27]
[Info   :   BepInEx] Loading [Infinity Hammer 1.32]
[Info   :   BepInEx] Loading [LeviathanNeverGoesAway By Laudriel 0.0.1]
[Info   :   BepInEx] Loading [HoneyPlus 5.2.0]
[Info   :HoneyPlus.HoneyPlus] Loaded asset bundle: honeyplusassets (UnityEngine.AssetBundle)
[Info   :   BepInEx] Loading [Blacksmithing 1.2.2]
[Info   :   BepInEx] Loading [TargetPortal 1.1.6]
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.1]
[Info   :   BepInEx] Loading [Better Pickup Notifications 1.3.1]
[Info   :   BepInEx] Loading [Epic Loot 0.9.10]
[Info   :   BepInEx] Loading [Extended Item Data Framework 1.0.11]
[Message:   BepInEx] Chainloader startup complete
[Info   :ModUtilsManagerLog] Processing Initial Load
[Info   :ModUtilsManagerLog] Fonts loaded
[Info   : Unity Log] BackpackRedux Searching for old backpack mod
[Info   : Unity Log] BackpackRedux Old plugin not found.
[Info   : Unity Log] 03/31/2023 11:38:09: Starting to load scene:start
[Message:Boneappetit.BoneAppetit] Loaded Game VFX and SFX
[Message:Boneappetit.BoneAppetit] Load Complete. Bone Appetit yall.
```

**Comment by sbtoonz** [comment]
Notes:

3.2.1 - hat was using standard shader
3.2.1 - flipped hat to ceature shader and used JVLMock system for shaders


0.3.3 - testing shader swapping at runtime with custom script 
V0.3.3 in my game

![image](https://user-images.githubusercontent.com/67915879/229168897-ff5dd64b-3dc4-4667-89e2-0fffcffeda7e.png)

Pleas test attached 3.2.3 and see if the issue persists..
[BoneAppetit.zip](https://github.com/RockerKitten/BoneAppetit/files/11123653/BoneAppetit.zip)

**Comment by TheCloudCrafter** [comment]
Wait its not the vanilla fire. its the mod fire.
Vanilla on left. Mod on right.
this is v3.2.2
![image](https://user-images.githubusercontent.com/53633953/229193112-b7d3a02c-0c7e-4de7-9866-5573017699d6.png)
![image](https://user-images.githubusercontent.com/53633953/229193095-5d1a70e5-9dd2-4316-ab00-ff6603d205cb.png)
![image](https://user-images.githubusercontent.com/53633953/229193069-00d8e29c-2f2b-457c-b85d-893be278ba7c.png)
![image](https://user-images.githubusercontent.com/53633953/229193045-c7f35476-e552-47bc-bd69-4966af068d56.png)

Testing v3.2.3 now.

**Comment by TheCloudCrafter** [comment]
v3.2.3
Same result.
I noticed the mod items also appear semi transparent.
![image](https://user-images.githubusercontent.com/53633953/229194455-4b43e30a-fb53-40ae-8236-0fbdfc24f4a4.png)

I had a that was wall mounted in my kitchen with error. 
But when i interacted it fixed and works fine. Odd.

textures also look lower quality.
bottom is vanilla top is mod

![image](https://user-images.githubusercontent.com/53633953/229194890-496144bf-ba78-4206-9eee-d42f1464c4bd.png)

**Comment by RockerKitten** [comment]
are you using Vulcan or "normal" launcher? or any other texture mods?

**Comment by TheCloudCrafter** [comment]
I used to use vulcan when I played vanilla, but now i launch with r2modman.
Launch options are: -console -window-mode exclusive
So i'm not declaring vulcan on load.

No texture / lighting mods. I prefer better frames.
If I have time this weekend I'll load a new world and check for a mod conflict. It'll take time tho.

**Comment by sbtoonz** [comment]
![image](https://user-images.githubusercontent.com/67915879/229206813-42297b3b-0ef7-4dec-bd85-0d3ba655fc1d.png)
[BoneAppetit.zip](https://github.com/RockerKitten/BoneAppetit/files/11125102/BoneAppetit.zip)


I updated the hearth model and made sure the smoke looks OK

Please test and let me know

If this persists I might have an idea of what is happening

**Comment by TheCloudCrafter** [comment]
Model updated. Looks good.
Shader error persists.

```
[Info   :   BepInEx] Loading [BoneAppetit 3.2.3]
[Message:Boneappetit.BoneAppetit] Prepping Kitchen...
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Message:Boneappetit.BoneAppetit] Big thanks to MeatwareMonster!

[Info   :ModUtilsManagerLog] Building GUI in startup
[Info   :ModUtilsManagerLog] Custom GUI Front & Back built and ready
[Message:Boneappetit.BoneAppetit] Loaded Game VFX and SFX
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Error  : Unity Log] Desired shader compiler platform 18 is not available in shader blob
[Message:Boneappetit.BoneAppetit] Load Complete. Bone Appetit yall.

```

![image](https://user-images.githubusercontent.com/53633953/229209114-bcde7639-6be5-43f7-b796-654f7060ce81.png)

**Comment by sbtoonz** [comment]
we're getting a little bit of headway, I can probably solve this by end of day then

**Comment by TheCloudCrafter** [comment]
Let me know what I can do to help. It's Friday so i may not be as free soon, but I'll do what I can.

**Comment by RockerKitten** [comment]
what version of Valheim are you using?

**Comment by TheCloudCrafter** [comment]
latest stable via steam.

I'm away from my desk now.

**Comment by TheCloudCrafter** [comment]
Confirmed. Patch 0.214.300

Let me know if you need a tester for a fix.

```
[Message:   BepInEx] BepInEx 5.4.21.0 - valheim (3/28/2023 8:42:17 PM)
[Info   :   BepInEx] Running under Unity v2020.3.45.6687953
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
```

**Comment by sbtoonz** [comment]
currently am unable to replicate this issue

I tried: clean install putting BA from thunderstore in - cannot replicate
Repairing install and putting BA from thunderstore in - cannot replicate

I didnt really fiddle with any in game graphical settings 

can you post those in a screen shot so we can rule out any nuances in that settings panel in my testing? 

Downloaded about 25 ish mods that I wanted to try out / used to use often and still was unable to replicate 


at this point I will have to test for incompatibility amongst your existing mods

Can you please provide me with a list of the mods ?

(the bootup part of bepin log should be good)

Or was the ammended version above a couple posts inclusive of all your current mods?

**Comment by TheCloudCrafter** [comment]
I'll try to replicate tomorrow if I can.
Yes the output I gave was a cleaned up log output with my mods.

**Comment by TheCloudCrafter** [comment]
@sbtoonz 

Found the issue.

I had launch params set to force Vulcan in steam. After disabling it works as intended. No issues with 3.2.2 or 3.2.4.
My performance went down a touch, but I'm still happy with it. 
Thank you very much for your time. It's odd that vulkan is no longer supported after 3.2.1. Not sure what changed.

**Comment by sbtoonz** [comment]
@RockerKitten  you can close this issue then :D  I will recompile with vulcan support

**Comment by TheCloudCrafter** [comment]
Closing issue as resolved. 
vNext add vulcan support

**Comment by TheCloudCrafter** [comment]
v 3.2.8 shader issue is back when on vulcan

**Comment by TheCloudCrafter** [comment]
@sbtoonz 
v 3.2.8 shader issue is back when on vulcan

**Comment by sbtoonz** [comment]
Haha ok I’ll resolve

**Comment by TheCloudCrafter** [comment]
Tested working on v 3.2.7 fine

**Comment by sbtoonz** [comment]
[BoneAppetit.zip](https://github.com/RockerKitten/BoneAppetit/files/11242907/BoneAppetit.zip)
@TheCloudCrafter  plz test

**Comment by TheCloudCrafter** [comment]
Issue persists
![image](https://user-images.githubusercontent.com/53633953/232333505-1e0c1f55-2c7b-478b-98ee-2ea1f4a3aedf.png)



v 3.2.8 also cannot refill fires. Wood is missing. 
Vanilla
![image](https://user-images.githubusercontent.com/53633953/232333391-f38c62eb-3457-41b6-850e-5064e0bf5b3f.png)
Mod
![image](https://user-images.githubusercontent.com/53633953/232333386-64ba5a02-cf30-42b2-b67b-ab98d9e791f2.png)

open new issue?

**Comment by TheCloudCrafter** [comment]
@sbtoonz  updated

**Comment by sbtoonz** [comment]
[BoneAppetit-BETA.zip](https://github.com/RockerKitten/BoneAppetit/files/11243216/BoneAppetit-BETA.zip)
ok... this should fix the wood in the fire issue as well as the shader issue 

please report back

**Comment by TheCloudCrafter** [comment]
shader issue fixed.
feeding fire fixed.
model still broken

![image](https://user-images.githubusercontent.com/53633953/232344079-487fec74-7ef4-4fc3-879f-4cd7aa438d20.png)

**Comment by TheCloudCrafter** [comment]
@sbtoonz reporting test results

shader issue fixed.
feeding fire fixed.
model still broken

new texture files?
![image](https://user-images.githubusercontent.com/53633953/232345325-648468ff-12ed-4998-afcc-c931cd043b09.png)
![image](https://user-images.githubusercontent.com/53633953/232345326-1a58e5e6-972e-4b8c-b74a-820624d639e3.png)
![image](https://user-images.githubusercontent.com/53633953/232345362-1c7079f5-cbd1-4631-b4d0-59339a986f7f.png)

**Comment by sbtoonz** [comment]
Bear with me I’ve had to repair the unity project

**Comment by TheCloudCrafter** [comment]
I'm in zero rush. Major bug is fixed. Rest is cosmetic. I'm happy just being a beta tester for you. 
I code in a different language so i get CI/CD.

**Comment by TheCloudCrafter** [comment]
@sbtoonz 
v 3.2.9 confirm fixed issue
