### ISSUE TITLE
Grill being destroyed as it's placed

### ISSUE THREAD

**Issue by ignistrix** [RockerKitten/BoneAppetit#30]
As title says the grill is being destroyed as it's placed, not sure if it's cause by the newest update to Jotunn. Just thought I'd make it known :) 

If any other info is needed please let me know!

**Comment by sbtoonz** [comment]
i will investigate

in the meantime can you change to the alternative grill style and see if it is also effected?

**Comment by sbtoonz** [comment]
Fixed in 3.2.6

**Comment by Goldensun03** [comment]
Hey sorry still happening for me 
only noticed when my existing grill suddenly broke 

also as  a side note why is the oven nearly impossible to place down?

**Comment by Goldensun03** [comment]
> > [BoneAppetit.zip](https://github.com/RockerKitten/BoneAppetit/files/11223240/BoneAppetit.zip) please test an report back
> 
> That seems to have done the trick! [https://imgur.com/zKO6CbA]

Hey sorry to bother you but how do I go about installing that please

**Comment by Mikandra** [comment]
It's still happening. I use the Thunderstore Mod Manager and updated the mod 20 hours ago, but I just realize that you fixed it 10 hours ago so I guess the fix is not in Thunderstore yet, right?

Thanks!

**Comment by sbtoonz** [comment]
3.2.7 should be showing soon in thunderstore

**Comment by Mikandra** [comment]
Great! now it works perfectly again, thank you!
